### ISSUE TITLE
bug: Anime not tracking

### ISSUE THREAD

**Issue by otDan** [aliyss/syncribullet#12]
Show: https://simkl.com/anime/1970434/dungeon-meshi
Can't see updates on either simkl or anilist

**Comment by otDan** [comment]
actually this seems to be more general, no anime are being tracked, at least the ones I am currently following

**Comment by aliyss** [comment]
Hiya... Working for me at list on simkl...

for some reason not working on anilist, but that can be because of title matching... Still working on that.

@Jenrykster have you had similar issues with your addon?

@otDan can you try readding the addon after removing and readding the credentials for simkl?

**Comment by otDan** [comment]
I have already tried removing and adding back the addon multiple times, it only does not track anime and I use it for simkl, shows and movies are tracked so I don't see how relogging and uninstalling again would change anything

**Comment by otDan** [comment]
https://web.stremio.com/#/detail/series/kitsu%3A46000
https://web.stremio.com/#/detail/series/kitsu%3A46320

**Comment by Jenrykster** [comment]
> @Jenrykster have you had similar issues with your addon?

I was having some trouble with Anilist returning 429 (too many requests) for some users, but seems to be working now.
It would be cool to implement a logging system to make debugging easier. Maybe check `beamup logs` if you haven't yet.

**Comment by aliyss** [comment]
@otDan Updated to support kitsu.

Can you check again? I don't know if you need to readd the addon or if it may be the cache on my side... but I had to readd the addon.

**Comment by otDan** [comment]
> @otDan Updated to support kitsu.
> 
> Can you check again? I don't know if you need to readd the addon or if it may be the cache on my side... but I had to readd the addon.

hmm I tried watching something after updating the addon but it seems to not track, I'll test it better later

**Comment by otDan** [comment]
I believe it tracks the wrong ones now, I was watching the latest season of demon slayer but it started marking a previous season that I already watched

**Comment by aliyss** [comment]
@otDan I changed the way I map the anime... probably should work again... No issues on my side when testing now... if you still have the error paste in the anime url you are watching.
