### ISSUE TITLE
Lists not updating

### ISSUE THREAD

**Issue by Naatan** [aliyss/syncribullet#15]
Hi there, I've installed both the receiver and sender, I see new lists under Discovery "eg. SIMKL TV Plan To Watch", but their contents don't seem to update. Even after checking back several hours later the contents are still outdated. Reinstalling the addon makes no difference.

I tried running syncribullet locally but it appears the instructions are outdated or there are things missing from the repo; no server directory exist. And the app that runs in browser has no Sender category.

**Comment by aliyss** [comment]
> Even after checking back several hours later the contents are still outdated. Reinstalling the addon makes no difference.
There is some caching running... I changed it. Feel free to test within an interval of 15min.

> no server directory exist
I think you may be missing the `npm run build` step.

> And the app that runs in browser has no Sender category.
You will need to redo the receivers. Sender only shows after at least one receiver is configured.

**Comment by Naatan** [comment]
Thanks @aliyss, will test tonight. Appreciate it 🙏

**Comment by aliyss** [comment]
Tested it on my own machine definitely works.
otherwise ping me.
