### ISSUE TITLE
Does not generate link to allow install on the strem.io app on Android

### ISSUE THREAD

**Issue by digfish** [aliyss/syncribullet#3]
Hi

I've tried to add the addon following the instructions on https://simkl.com/apps/stremio/ , going to the site on https://56bca7d190fc-syncribullet.baby-beamup.club/ I go redirected to the simkl website, aprove the app access on simkl and I'm redirect again to the addon site above, I click to follow the link to install the addon on strem.io but nothing happens.
Note: I managed to install the addon on the stremio client under windows. It appears on the addons list under the windows client but when I click the cogwheel button on the addon the browser opens the link https://56bca7d190fc-syncribullet.baby-beamup.club/simkl_accesstoken-=<some_access_token_here>-=-/configure but results in a 404 page.
The addon now appears on the android client, but there was not a way to add it under Android.

**Comment by aliyss** [comment]
Ah yes...

Okay so these are two separate things:

1) Add-on is not added via android.

This is probably an issue on stremio's side, where adding the add-on only works if stremio is already open

2) No configure option for already configured stuff...

This needs to be fixed on my end.

---
Thanks for the heads-up

**Comment by aliyss** [comment]
@digfish Closing this as I fixed it up a bit. I think this should work now.

**Comment by digfish** [comment]
Hi
I saw the settings page, I confirm it's working now.
On the settings it is possible to add an option to choose to make the sync
at the end of the video? At now, it appears to do it at the beginning. It's
more logic that the sync is made at the end instead of the beginning.
Anyway, thanks for what you have done. Keep up the good work.

Cheers

A terça, 2/01/2024, 14:19, Aliyss Snow ***@***.***> escreveu:

**Comment by aliyss** [comment]
> It's more logic that the sync is made at the end instead of the beginning.

Absolutely agree... This is a limitation on stremio's end. I am currently abusing the subtitle manager to track watches. Stremio does not give events to when a video starts or ends.
