### ISSUE TITLE
Removing Receivers

### ISSUE THREAD

**Issue by nyuuke** [aliyss/syncribullet#5]
I am unable to remove previously added receivers. I recently added AniList but there doesn't seem to be an option to remove it from the website nor change it. I just want to keep SIMKL for now.

**Comment by aliyss** [comment]
Hiya

Known Issue.
https://github.com/aliyss/syncribullet?tab=readme-ov-file#known-issues

> Authentication Tokens are stored in localstorage. This is because of the issue above, so you don’t have to reauthenticate everytime you configure the addon. Current Workaround: Manually clear localstorage after the setup if you want to.

You'll also have to update the addon afaik. I'll see that I can add a button in the near future.

**Comment by aliyss** [comment]
@nyuuke I added a remove authentication button...

Try clicking on that and then readd the addon.
A confirmation would be nice. ^^

Best, aliyss

**Comment by nyuuke** [comment]
Thank you so much! :)

**Comment by ericvlog** [comment]
all poster at android tv stremio show up ~~!! thanks !!
