### ISSUE TITLE
Watched episode is displayed as +1 from actual 

### ISSUE THREAD

**Issue by d1zmal** [aliyss/syncribullet#7]
Eg If I'm watching s04e03, Syncribullet seems to be passing s04e04 to simkl.

Tested with a few shows

**Comment by aliyss** [comment]
I just tested it with "True Detective" as an example seemed to work on my end.

Do you have specific shows I could test?

**Comment by d1zmal** [comment]
Hi, thanks for your reply

It's happening consistently for me with three shows I tested, being:
Halo, playing s02e01 shows s02e02 in progress.
True Detective s04e03 as s04e04 in progress.
Shogun s01e01 as s01e02 in progress.

**Comment by aliyss** [comment]
This is wierd. Did you already try removing and readding the addon and trying again... Otherwise we may have to test it someway differently

**Comment by d1zmal** [comment]
I've only just tried uninstalling and reinstalling. Appears to be doing the same thing, unfortunately.

![Screenshot_20240305_202715_Stremio.jpg](https://github.com/aliyss/syncribullet/assets/19987916/7955cedf-d4dc-44dd-a2b0-c86606640282)

![Screenshot_20240305_202742_Simkl Lists.jpg](https://github.com/aliyss/syncribullet/assets/19987916/57da3147-037b-4f91-ae81-5e3c54a36649)

**Comment by aliyss** [comment]
What is the current version of the add-on?

**Comment by d1zmal** [comment]
v1.0.13

I follow that the sync is immediate but only the episode I just started should appear in 'Seen', right?
E.g. I start watching s02e01; watched state of s02e01 is synchronised to Simkl and episode is marked as Seen.

**Comment by aliyss** [comment]
I'm wondering if another add-on may be sending the info to the server. This way I may be able to reproduce your setup.

If you can't list your add-ons publicly, feel free to join my discord server and DM me from there.
