### ISSUE TITLE
Movies do not sync on Simkl

### ISSUE THREAD

**Issue by Alltornadoes** [aliyss/syncribullet#8]
While shows watched on Stremio sync perfectly with Simkl, watched movies just don't appear in Simkl's "I've seen this list". It worked once for a movie then stopped working, whereas shows keep syncing without any issue.

Adding to the above, I have also noticed that an episode syncs to Simkl as watched althout I have not completed it on Stremio. I have Utorrentio and TPB installed as addons from where I stream.

**Comment by aliyss** [comment]
Ok. So this should now be fixed. I also notice Anilist movies not syncing so that is fixed too.

If you could quickly validate everything is working that would be great.

**Comment by Alltornadoes** [comment]
I tried a couple of movies and indeed they now sync, so great work and thank you. I do not use Anilist so I cannot check that. 

Only a small remark, movies sync as watched as soon as they start playing, which is not a big deal, but is there a way for them to sync upon completion instead? 
For shows episodes it does not matter, since most people would watch an episode in one sitting. However for movies it could be different, where some people might watch them in one or two sittings instead of in just a single sitting.

Anyway thank you for resolving the issue promptly.

**Comment by aliyss** [comment]
Good to know it's working again.

Concerning the Watch Progress (handling it here): https://github.com/aliyss/syncribullet/issues/6
